name: build 

on: push 

jobs:
  build_and_test:
    name: Build and run Unit Tests
    runs-on: ubuntu-latest
    steps:
        ##########################
        # Checkout the code base #
        ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

        ################################
        # Run Linter against code base #
        ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        ##########################
        # Setup Java 11          #
        ##########################
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

        ##########################
        # Execute Unit Tests     #
        ##########################
      - name: Run Unit Tests
        run: mvn test

      - uses: AppThreat/sast-scan-action@master
        with:
          type: "java"

      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
            