name: build and run unit tests

on: 
  push:

env:
  UAT_IP: 3.16.21.252
  UAT_PORT: 22

jobs:
  build_and_test_and_deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./pom.xml

      - name: rename Artefakt
        run: mv ./target/*digitalbank*.war ./target/digibank.war

      - uses: actions/upload-artifact@master
        with:
          name: digibank.war
          path: ./target/digibank*
          
      - name: 'cleanup destination at $UAT_IP'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          script: rm -rf ./deployment/*

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          source: './target/digibank.war'
          target: 'deployment'
          debug: true
