name: scp files
on: [push]
jobs:
  build:
    environment: UAT
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./pom.xml

      - name: rename Artefakt
        run: mv ./target/*digitalbank*.war ./target/digibank.war

      - uses: actions/upload-artifact@master
        with:
          name: digibank.war
          path: ./target/digibank*

  deploy:
    needs: build
    environment: UAT
    name: Deploy Application on Enviroment
    runs-on: ubuntu-latest

    steps:
      - name: get Artefakt
        uses: actions/download-artifact@master
        with:
          name: digibank.war
          path: ~ #/home/runner/work/digital-bank/digital-bank

      - name: cleanup destination
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: rm -rf ./deployment/

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: '/home/runner/work/digital-bank/digital-bank/digibank.war'
          target: '~/deployment/'

  install:
    needs: deploy
    environment: UAT
    name: Install Application
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: cp /home/ubuntu/deployment/github/workspace/digibank.war /opt/tomcat/webapps/

    automation_tests:
      needs: install
      environment: UAT
      name: Trigger E2E Tests
      runs-on: ubuntu-latest

      steps:
        - name: Trigger Workflow from e2e tests with Playwright
          run: |
            curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/e2e-pipeline-workshop/digibank-playwright-tests/actions/workflows/run-tests.yml/dispatches \
            -d '{"ref": "master", "tmp": "UAT" }'
